#baseURL = "https://chilcano.github.io/ghpages-holosecio/"
baseURL = "https://holisticsecurity.io/"
languageCode = "en-us"
title = "Holistic Security"
theme = "hugo-theme-cactus"
publishDir = "../ghp-content/docs"
#copyright = "Roger Carhuatocto"
#disqusShortname = "username"
googleAnalytics = "UA-156433649-1"
paginate = 12
#summaryLength = 2

###### Main menu which appears below site header.

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Writings"
  url = "/post"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3
[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "white"                        # dark, light, white, or classic
  rss = true                                  # generate rss feed. default value is false
  #googleAnalyticsAsync = true                 # use asynchronous tracking. Synchronous tracking by default (info: https://gohugo.io/templates/internal/)

  # Home page settings
  description = "With The Systems Thinking Methodology we are able to see any problem in a complete and holistic manner, in fact, The Systems Thinking Methodology allows us to solve complex problems (IT Security, Global Warming, World Poverty, etc.) by considering new factors, elements and variables (usability, trust, quality, risk, etc.) which were not considered initially."
  #mainSection = "posts"                      # your main section
  showAllPostsOnHomePage = false              # default
  postsOnHomePage = 10                        # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false                         # show tags overview by default.
  showProjectsList = true                     # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/chilcano" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"                   # default

  # Post page settings
  show_updated = false                        # default

  custom_css = ["css/custom-cactus-style-white.css"]

  [params.comments]
    enabled = false                           # default
    engine = "disqus"                         # more supported engines will be added.

#### the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands

[[params.social]]
  name = "github"
  link = "https://github.com/chilcano"
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/chilcano"
[[params.social]]
  name = "twitter"
  link = "https://twitter.com/chilcano" 

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  preserveTaxonomyNames = true