---
name: Test

on:
  push:
    branches:
      - 'tests/**'

jobs:
  get_and_print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x
      #     cache: 'npm'
      - name: Get variables
        id: vars1
        run: |
          echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )"
          echo "::set-output name=commit_hash_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=commit_hash::$(git rev-parse HEAD)"
          echo "::set-output name=committer::${GITHUB_ACTOR}"
          echo "actor=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT

      - name: Print variables
        run: |
          echo "=> GH_REFS: ${GITHUB_REF#refs/heads/}"
          echo "=> COMMITTER: ${{ steps.vars1.outputs.committer }}"
          echo "=> BRANCH_NAME: ${{ steps.vars1.outputs.branch_name }}"
          echo "=> COMMIT_HASH: ${{ steps.vars1.outputs.commit_hash }}"
          echo "=> COMMIT_HASH_SHORT: ${{ steps.vars1.outputs.commit_hash_short }}"
          echo "=> ACTOR: ${{ steps.vars1.outputs.actor }}"
          